name: RegionPlugin
version: '${project.version}'
main: com.io.region.region.plugin.RegionPlugin
api-version: 1.16
commands:
  region:
    description: region command
  area:
    description: area command
  member:
    description: member command